-- Criando o banco de dados
CREATE DATABASE NOTA_FISCAL_NORMALIZADA;
USE `NOTA_FISCAL_NORMALIZADA`;

-- Criando a tabela NOTA_FISCAL
CREATE TABLE `NOTA_FISCAL` (
    `NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NM_CLIENTE` VARCHAR(256) NOT NULL,
    `END_CLIENTE` VARCHAR(256) NOT NULL,
    `NM_VENDEDOR` VARCHAR(256) NOT NULL,
    `DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `VL_TOTAL` FLOAT NOT NULL
);

-- Criando a tabela PRODUTO
CREATE TABLE `PRODUTO` (
    `COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESC_PRODUTO` VARCHAR(256) NOT NULL,
    `UN_MED` CHAR(2) NOT NULL,
    `VL_PRODUTO` FLOAT NOT NULL
);

-- Criando a tabela ITEM_NOTA_FISCAL
CREATE TABLE `ITEM_NOTA_FISCAL` (
    `NRO_NOTA` INT NOT NULL,
    `COD_PRODUTO` INT NOT NULL,
    `QTD_PRODUTO` INT NOT NULL,
    `VL_PRECO` FLOAT NOT NULL,
    `VL_TOTAL` FLOAT NOT NULL,
    PRIMARY KEY (`NRO_NOTA`, `COD_PRODUTO`),
    CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL
        FOREIGN KEY (`NRO_NOTA`) REFERENCES `NOTA_FISCAL` (`NRO_NOTA`),
    CONSTRAINT FK_COD_PRODUTO_PRODUTO
        FOREIGN KEY (`COD_PRODUTO`) REFERENCES `PRODUTO` (`COD_PRODUTO`)
);

-- Inserindo produtos
INSERT INTO `PRODUTO` (`DESC_PRODUTO`, `UN_MED`, `VL_PRODUTO`) VALUES 
('LEITE', 'LT', 5.40),
('DESODORANTE', 'UN', 11.99),
('SALAME', 'KG', 40.00);

-- Inserindo notas fiscais
INSERT INTO `NOTA_FISCAL` (`NM_CLIENTE`, `END_CLIENTE`, `NM_VENDEDOR`, `VL_TOTAL`) VALUES 
('ARAGORN', 'TERRA MÉDIA', 'BILBO', 100.00),
('GANDALF', 'TERRA MÉDIA', 'FRODO', 100.00),
('BOROMIR', 'MORDOR', 'SAM', 100.00),
('GALADRIEL', 'VALINOR', 'SARUMAN', 100.00);

-- Inserindo itens nas notas fiscais
INSERT INTO `ITEM_NOTA_FISCAL` (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`) VALUES 
(1, 1, 1, 5.40, 5.40),
(1, 2, 2, 11.99, 23.98),
(1, 3, 1, 40.00, 40.00),

(2, 1, 2, 5.40, 10.80),
(2, 2, 1, 11.99, 11.99),
(2, 3, 2, 40.00, 80.00),

(3, 1, 1, 5.40, 5.40),
(3, 2, 3, 11.99, 35.97),
(3, 3, 1, 40.00, 40.00),

(4, 1, 2, 5.40, 10.80),
(4, 2, 2, 11.99, 23.98),
(4, 3, 1, 40.00, 40.00);

-- Selecionando todos os itens da nota fiscal
SELECT * FROM `ITEM_NOTA_FISCAL`;

-- Buscando um produto específico
SELECT * FROM `PRODUTO` WHERE `COD_PRODUTO` = 3;

-- Atualizando um produto
UPDATE `PRODUTO`
SET `VL_PRODUTO` = 45.00, `DESC_PRODUTO` = 'Atualizado', `UN_MED` = 'CX'
WHERE `COD_PRODUTO` = 3;

-- Excluindo um produto
DELETE FROM `PRODUTO` 
WHERE `COD_PRODUTO` = 3;

INSERT INTO PRODUTO  (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Teste delete', 'LT', 5.50);

SELECT * FROM PRODUTO;

DELETE FROM PRODUTO WHERE COD_PRODUTO = 4;

