-- CRIAR BD 
CREATE DATABASE GREENHOUSE;

-- DEFINIR BD COMO PADRÃO / UTILIZAVEL
USE GREENHOUSE;

-- CRIAR TABLE/ENTIDADE
CREATE TABLE `PLANTS` (
  `PLANT_NAME` CHAR(30) NOT NULL,
  `SENSOR_VALUE` FLOAT DEFAULT NULL,
  `SENSOR_EVENT` TIMESTAMP NOT NULL 
		DEFAULT CURRENT_TIMESTAMP 
		ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY `PK_PLANTS` (`PLANT_NAME`)
);


-- VISUALIZAR TODAS AS OCORRENCIAS EM PLANTS
-- LISTAR TODOS O SREGISTROS DE DADOS
SELECT * FROM `PLANTS`;
SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM PLANTS;

-- INSERIR DADOS NA TABELA/ENTIDADES PLANTS

INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES ('MACONHAO', 0.2319 );

-- INSERIR MULTIPLOS REGISTROS DE UMA VEZ
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES ('CACTOS', 0.2411),
	   ('ORQUIDEA', 0.34112),
       ('LIRIO', 0.5566),
       ('GIRASSOL', 0.3112);
       
SELECT * 
FROM PLANTS
WHERE PLANT_NAME = 'CACTOS';

SELECT * 
FROM PLANTS
WHERE PLANT_NAME <> 'CANABIS'
AND SENSOR_VALUE < 0.5566
AND SENSOR_VALUE > 0.2411;