-- Criação do Banco de Dados
CREATE DATABASE VETERINARIA;

USE VETERINARIA;

CREATE TABLE TIPO_ANIMAL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE ANIMAL (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ID_TIPO_ANIMAL INT NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    COR VARCHAR(50),
    PESO FLOAT,
    ALTURA FLOAT,
    CONSTRAINT FK_ID_TIPO_ANIMAL_ANIMAL
        FOREIGN KEY (ID_TIPO_ANIMAL)
        REFERENCES TIPO_ANIMAL(ID)
);


CREATE TABLE VACINA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_APLICACAO DATE NOT NULL,
    ID_ANIMAL INT NOT NULL,
    CONSTRAINT FK_ID_ANIMAL_VACINA
        FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAL(ID)
);

-- Adicionando índices (opcional, para melhorar a performance em buscas)
CREATE INDEX IDX_ANIMAL_TIPO_ANIMAL
    ON ANIMAL (ID_TIPO_ANIMAL);

CREATE INDEX IDX_VACINA_ID_ANIMAL
    ON VACINA (ID_ANIMAL);

-- Inserção de Dados de Exemplo

-- Inserindo Tipos de Animais
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('CANINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('FELINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('SUÍNO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('CAPRINO');
INSERT INTO TIPO_ANIMAL (NOME) VALUES ('EQUINO');

-- Inserindo Animais
INSERT INTO ANIMAL (NOME, ID_TIPO_ANIMAL, DT_NASCIMENTO, COR, PESO, ALTURA) 
VALUES ('Rex', 1, '2018-05-01', 'Marrom', 25.5, 0.8); -- Exemplo de CANINO
INSERT INTO ANIMAL (NOME, ID_TIPO_ANIMAL, DT_NASCIMENTO, COR, PESO, ALTURA) 
VALUES ('Miau', 2, '2019-08-15', 'Preto', 4.2, 0.4); -- Exemplo de FELINO

-- Inserindo Vacinas
INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina Antirrábica', '2023-06-15', 1); -- Exemplo de vacina para o CANINO
INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina V8', '2023-07-20', 1); -- Exemplo de outra vacina para o CANINO

INSERT INTO VACINA (NOME, DATA_APLICACAO, ID_ANIMAL) 
VALUES ('Vacina Felina', '2023-09-05', 2); -- Exemplo de vacina para o FELINO
